local help_message = [[
This is a module file for the container biocontainers/poretools:v0.6.0dfsg-2-deb_cv1, which exposes the
following programs:

 - chardet
 - cpp-6
 - createfontdatachunk.py
 - dh_numpy
 - enhancer.py
 - explode.py
 - f2py2.7
 - g++-6
 - gcc-6
 - gcc-ar-6
 - gcc-nm-6
 - gcc-ranlib-6
 - gcov-6
 - gcov-dump
 - gcov-dump-6
 - gcov-tool-6
 - gifmaker.py
 - nosetests
 - nosetests-2.7
 - painter.py
 - pilconvert.py
 - pildriver.py
 - pilfile.py
 - pilfont.py
 - pilprint.py
 - player.py
 - poretools
 - pt2to3
 - ptdump
 - ptrepack
 - pttree
 - py.test
 - pytest
 - runxlrd
 - thresholder.py
 - viewer.py
 - x86_64-linux-gnu-cpp-6
 - x86_64-linux-gnu-g++-6
 - x86_64-linux-gnu-gcc-6
 - x86_64-linux-gnu-gcc-ar-6
 - x86_64-linux-gnu-gcc-nm-6
 - x86_64-linux-gnu-gcc-ranlib-6
 - x86_64-linux-gnu-gcov-6
 - x86_64-linux-gnu-gcov-dump
 - x86_64-linux-gnu-gcov-dump-6
 - x86_64-linux-gnu-gcov-tool-6

This container was pulled from:

	https://hub.docker.com/r/biocontainers/poretools

If you encounter errors in poretools or need help running the
tools it contains, please contact the developer at

	https://github.com/arq5x/poretools

For errors in the container or module file, please
submit a ticket at

	gzynda@tacc.utexas.edu
	https://portal.tacc.utexas.edu/tacc-consulting
]]
help(help_message,"\n")

whatis("Name: poretools")
whatis("Version: ctr-v0.6.0dfsg-2-deb_cv1")
whatis("Category: ['Nucleic acid sequence analysis']")
whatis("Keywords: ['DNA', 'Sequencing']")
whatis("Description: Flexible toolkit for exploring datasets generated by nanopore sequencing devices from MinION for the purposes of quality control and downstream analysis.")
whatis("URL: https://hub.docker.com/r/biocontainers/poretools")

set_shell_function("chardet",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg chardet $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg chardet $*')
set_shell_function("cpp-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg cpp-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg cpp-6 $*')
set_shell_function("createfontdatachunk.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg createfontdatachunk.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg createfontdatachunk.py $*')
set_shell_function("dh_numpy",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg dh_numpy $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg dh_numpy $*')
set_shell_function("enhancer.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg enhancer.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg enhancer.py $*')
set_shell_function("explode.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg explode.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg explode.py $*')
set_shell_function("f2py2.7",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg f2py2.7 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg f2py2.7 $*')
set_shell_function("g++-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg g++-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg g++-6 $*')
set_shell_function("gcc-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-6 $*')
set_shell_function("gcc-ar-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-ar-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-ar-6 $*')
set_shell_function("gcc-nm-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-nm-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-nm-6 $*')
set_shell_function("gcc-ranlib-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-ranlib-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcc-ranlib-6 $*')
set_shell_function("gcov-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-6 $*')
set_shell_function("gcov-dump",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-dump $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-dump $*')
set_shell_function("gcov-dump-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-dump-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-dump-6 $*')
set_shell_function("gcov-tool-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-tool-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gcov-tool-6 $*')
set_shell_function("gifmaker.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gifmaker.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg gifmaker.py $*')
set_shell_function("nosetests",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg nosetests $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg nosetests $*')
set_shell_function("nosetests-2.7",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg nosetests-2.7 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg nosetests-2.7 $*')
set_shell_function("painter.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg painter.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg painter.py $*')
set_shell_function("pilconvert.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilconvert.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilconvert.py $*')
set_shell_function("pildriver.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pildriver.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pildriver.py $*')
set_shell_function("pilfile.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilfile.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilfile.py $*')
set_shell_function("pilfont.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilfont.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilfont.py $*')
set_shell_function("pilprint.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilprint.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pilprint.py $*')
set_shell_function("player.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg player.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg player.py $*')
set_shell_function("poretools",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg poretools $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg poretools $*')
set_shell_function("pt2to3",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pt2to3 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pt2to3 $*')
set_shell_function("ptdump",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg ptdump $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg ptdump $*')
set_shell_function("ptrepack",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg ptrepack $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg ptrepack $*')
set_shell_function("pttree",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pttree $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pttree $*')
set_shell_function("py.test",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg py.test $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg py.test $*')
set_shell_function("pytest",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pytest $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg pytest $*')
set_shell_function("runxlrd",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg runxlrd $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg runxlrd $*')
set_shell_function("thresholder.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg thresholder.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg thresholder.py $*')
set_shell_function("viewer.py",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg viewer.py $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg viewer.py $*')
set_shell_function("x86_64-linux-gnu-cpp-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-cpp-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-cpp-6 $*')
set_shell_function("x86_64-linux-gnu-g++-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-g++-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-g++-6 $*')
set_shell_function("x86_64-linux-gnu-gcc-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-6 $*')
set_shell_function("x86_64-linux-gnu-gcc-ar-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-ar-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-ar-6 $*')
set_shell_function("x86_64-linux-gnu-gcc-nm-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-nm-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-nm-6 $*')
set_shell_function("x86_64-linux-gnu-gcc-ranlib-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-ranlib-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcc-ranlib-6 $*')
set_shell_function("x86_64-linux-gnu-gcov-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-6 $*')
set_shell_function("x86_64-linux-gnu-gcov-dump",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-dump $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-dump $*')
set_shell_function("x86_64-linux-gnu-gcov-dump-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-dump-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-dump-6 $*')
set_shell_function("x86_64-linux-gnu-gcov-tool-6",'singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-tool-6 $@','singularity exec ${BIOCONTAINER_DIR}/biocontainers/poretools/poretools-v0.6.0dfsg-2-deb_cv1.simg x86_64-linux-gnu-gcov-tool-6 $*')
